import sys
import os

PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))
try:
    from climateserv2.processtools import dateIndexTools as dit
except ImportError:
    from .processtools import dateIndexTools as dit

DEBUG_LIVE = False
logToConsole = True
pythonPath = '''/home/tethys/miniconda/envs/ClimateSERV2/bin/python'''
serviringestroot = '''/cserv2/tmp/data/pythonCode/serviringest/'''
dbfilepath = '''/cserv2/tmp/servirchirps.db'''
newdbfilepath = '''/cserv2/tmp/servirchirps_bsddb.db'''
capabilities_db_filepath = '''/cserv2/tmp/servirchirps_bsddb_capabilities.db'''
requestLog_db_basepath = '''/cserv2/tmp/'''
zipFile_ScratchWorkspace_Path = '''/mnt/cs-temp/request_out/'''  # '''/cserv2/tmp/zipout/Zipfile_Scratch/'''
logfilepath = '''/cserv2/tmp/'''
workpath = '''/cserv2/tmp/'''
shapefilepath = '''/cserv2/tmp/mapfiles/'''
ageInDaysToPurgeData = 7
nmme_ccsm4_path = '''/mnt/climateserv/nmme-ccsm4_bcsd/global/0.5deg/daily/latest/'''  # '''/cserv2/tmp/data/nmme/'''
nmme_cfsv2_path = '''/mnt/climateserv/nmme-cfsv2_bcsd/global/0.5deg/daily/latest/'''
base_data_path = '/mnt/climateserv/'  # '''/mnt/climateserv/ucsb-chirps/global/0.05deg/daily/'''
parameters = [[0, 'max', "Max"], [1, 'min', "Min"], [2, 'median', "Median"], [3, 'range', "Range"], [4, 'sum', "Sum"],
              [5, 'avg', 'Average'], [6, 'download', 'Download'], [7, 'netcdf', 'NetCDF'], [8, 'csv', 'CSV']]

def get_dataLocation(type):
    path = ""
    if type == "ucsb-chirps":
        path = 'process_tmp/fast_chirps/'
    elif type == "ucsb-chirp":
        path = 'process_tmp/fast_chirp/'
    elif type == "ucsb-chirps-gefs":
        path = 'process_tmp/fast_chirps_gefs/'
    elif type == "nmme-ccsm4_bcsd" or type == "nmme-cfsv2_bcsd":
        path = type + '/global/0.05deg/daily/latest/'
    elif type == "usda-smap":
        path = 'process_tmp/fast_usda_smap/'
    elif type == "centralasia" or type == "westafrica" or type == "eastafrica" or type == "southernafrica":
        path = 'process_tmp/fast_emodis_' + type + '/'
    elif type == "sport-esi/12wk":
        path = 'process_tmp/fast_sport_esi_12wk/'
    elif type == "sport-esi/4wk":
        path = 'process_tmp/fast_sport_esi_4wk/'
    elif type == "nasa-imerg-late":
        path = 'process_tmp/fast_nasa_imerg_late_daily/'
    elif type == "nasa-imerg-early":
        path = 'process_tmp/fast_nasa_imerg_early_daily/'
    return base_data_path + path


# To get the file path of a CCSM4 file
def get_ClimateChangeParam__inputDataLocation(ensembleName):
    return nmme_ccsm4_path + 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.' + ensembleName + '.nc4'


# To get the file path of a CSFV2 file
def get_ClimateChangeParam__inputDataLocation_cfsv2(ensembleName):
    return nmme_cfsv2_path + 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.' + ensembleName + '.nc4'


# To get size
def get_ClimateChangeParam__size():
    return [720, 360]


# to get fill value
def get_ClimateChangeParam__fillValue():
    return -9999.


# To get an indexer
def get_ClimateChangeParam__indexer():
    return dit.DailyIndex()


# to get number of forecast days
def get_ClimateChangeParam__number_Of_ForecastDays():
    return 180


dataTypes = [
    {'number': 0,
     'name': 'Chirps', 'description': 'Global CHIRPS Dataset ',
     'size': [7200, 2000],
     'directory': '/cserv2/tmp/chirps/',
     'fillValue': -9999.,
     'indexer': dit.DailyIndex(),
     'inputDataLocation': get_dataLocation("ucsb-chirps"),
     'data_category': 'CHIRPS',
     'variable': 'precipitation_amount',
     'dataset_name': 'ucsb-chirps_global_0.05deg_daily',
     },

    {'number': 1,
     'name': 'NDVI MODIS-West Africa',
     'description': 'NDVI MODIS West Africa description',
     'size': [19272, 7875],
     'directory': '/data/data/image/processed/eMODIS/ndvi-westafrica/',
     'fillValue': -9999.,
     'indexer': dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("westafrica"),
     'data_category': 'NDVI',
     'variable': 'ndvi',
     'dataset_name': 'emodis-ndvi_westafrica_250m_10dy',
     },

    {'number': 2,
     'name': 'NDVI MODIS-East Africa',
     'description': 'NDVI MODIS East Africa description',
     'size': [12847, 14713],
     'directory': '/data/data2/image/processed/eMODIS/ndvi-eastafrica/np/',
     'fillValue': -9999.,
     'indexer': dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("eastafrica"),
     'data_category': 'NDVI',
     'variable': 'ndvi',
     'dataset_name': 'emodis-ndvi_eastafrica_250m_10dy',
     },

    {'number': 3,
     'name': 'NDVI MODIS-North Africa', 'description': 'NDVI MODIS North Africa description',
     'size': [23415, 7045],
     'directory': '/data/data/image/processed/eMODIS/ndvi-northafrica/np/',
     'fillValue': -9999.,
     'indexer': dit.EveryFiveDaysIndex(),
     'inputDataLocation': '/data/data/image/input/emodis/northafrica/',
     'data_category': 'NDVI',
     },

    {'number': 4,
     'name': 'NDVI MODIS-Central Africa',
     'description': 'NDVI MODIS Central Africa description',
     'size': [1600, 1500],
     'directory': '/data/data/image/processed/eMODIS/ndvi-centralafrica/np/',
     'fillValue': -9999.,
     'indexer': dit.EveryFiveDaysIndex(),
     'inputDataLocation': '/data/data/image/input/emodis/centralafrica/',
     'data_category': 'NDVI',
     },

    {'number': 5, 'name': 'NDVI MODIS-South Africa',
     'description': 'NDVI MODIS South Africa description',
     'size': [19839, 17001],
     'directory': '/data/data2/image/processed/eMODIS/ndvi-southafrica/np/',
     'fillValue': -9999.,
     'indexer': dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("southernafrica"),
     'data_category': 'NDVI',
     'variable': 'ndvi',
     'dataset_name': 'emodis-ndvi_southernafrica_250m_10dy',
     },

    # Adding new climate change datatypes here.
    # Ensemble 01
    {
        'number': 6,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens01',
        'ensemble_Label': 'Ensemble 01', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens01 Temperature',
        'description': 'Climate Change Scenario: ens01 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens001'),
        'size': get_ClimateChangeParam__size(),  # [720,360]
        'fillValue': get_ClimateChangeParam__fillValue(),  # -9999.,
        'indexer': get_ClimateChangeParam__indexer(),  # dit.DailyIndex(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),  # 180
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens001',
    },

    {
        'number': 7,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens01',
        'ensemble_Label': 'Ensemble 01', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens01 Precipitation',
        'description': 'Climate Change Scenario: ens01 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens001'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens001',
    },

    # Ensemble 02
    {
        'number': 8,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens02',
        'ensemble_Label': 'ensemble 02', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens02 Temperature',
        'description': 'Climate Change Scenario: ens02 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens002'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens002',
    },

    {
        'number': 9,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens02',
        'ensemble_Label': 'Ensemble 02', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens02 Precipitation',
        'description': 'Climate Change Scenario: ens02 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens002'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens002',
    },

    # Ensemble 03
    {
        'number': 10,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens03',
        'ensemble_Label': 'ensemble 03', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens03 Temperature',
        'description': 'Climate Change Scenario: ens03 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens003'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens003',
    },

    {
        'number': 11,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens03',
        'ensemble_Label': 'Ensemble 03', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens03 Precipitation',
        'description': 'Climate Change Scenario: ens03 Variable: Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens003'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens003',
    },

    # Ensemble 04
    {
        'number': 12,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens04',
        'ensemble_Label': 'ensemble 04', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens04 Temperature',
        'description': 'Climate Change Scenario: ens04 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens004'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens004',
    },

    {
        'number': 13,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens04',
        'ensemble_Label': 'Ensemble 04', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens04 Precipitation',
        'description': 'Climate Change Scenario: ens04 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens004'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens004',
    },

    # Ensemble 05
    {
        'number': 14,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens05',
        'ensemble_Label': 'ensemble 05', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens05 Temperature',
        'description': 'Climate Change Scenario: ens05 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens005'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens005',
    },

    {
        'number': 15,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens05',
        'ensemble_Label': 'Ensemble 05', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens05 Precipitation',
        'description': 'Climate Change Scenario: ens05 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens005'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens005',
    },

    # Ensemble 06
    {
        'number': 16,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens06',
        'ensemble_Label': 'ensemble 06', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens06 Temperature',
        'description': 'Climate Change Scenario: ens06 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens006'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens006',
    },

    {
        'number': 17,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens06',
        'ensemble_Label': 'Ensemble 06', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens06 Precipitation',
        'description': 'Climate Change Scenario: ens06 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens006'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens006',
    },

    # Ensemble 07
    {
        'number': 18,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens07',
        'ensemble_Label': 'ensemble 07', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens07 Temperature',
        'description': 'Climate Change Scenario: ens07 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens007'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens007',
    },

    {
        'number': 19,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens07',
        'ensemble_Label': 'Ensemble 07', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens07 Precipitation',
        'description': 'Climate Change Scenario: ens07 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens007'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens007',
    },

    # Ensemble 08
    {
        'number': 20,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens08',
        'ensemble_Label': 'ensemble 08', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens08 Temperature',
        'description': 'Climate Change Scenario: ens08 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens008'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens008',
    },

    {
        'number': 21,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens08',
        'ensemble_Label': 'Ensemble 08', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens08 Precipitation',
        'description': 'Climate Change Scenario: ens08 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens008'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens008',
    },

    # Ensemble 09
    {
        'number': 22,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens09',
        'ensemble_Label': 'ensemble 09', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens09 Temperature',
        'description': 'Climate Change Scenario: ens09 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens009'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens009',
    },

    {
        'number': 23,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens09',
        'ensemble_Label': 'Ensemble 09', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens09 Precipitation',
        'description': 'Climate Change Scenario: ens09 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens009'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens009',
    },

    # Ensemble 10
    {
        'number': 24,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens10',
        'ensemble_Label': 'ensemble 10', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens10 Temperature',
        'description': 'Climate Change Scenario: ens10 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens010'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens010',
    },

    {
        'number': 25,
        'data_category': 'ClimateModel',
        'ensemble': 'ccsm4_ens10',
        'ensemble_Label': 'Ensemble 10', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens10 Precipitation',
        'description': 'Climate Change Scenario: ens10 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation('ens010'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-ccsm4_bcsd.latest.global.0.5deg.daily.ens010',
    },

    # End First batch of ClimateModel datasets

    # IMERG Precip, GPM
    {'number': 26,
     'name': 'IMERG 1 Day',
     'description': 'GPM IMERG Daily Accumulation Precip',
     'size': [3600, 1800],
     'directory': '/data/data2/image/processed/IMERG1Day/',
     'fillValue': 9999.,
     'indexer': dit.DynamicIndex("P1D"),
     'inputDataLocation': get_dataLocation("nasa-imerg-late"),
     'data_category': 'IMERG',
     'variable': 'precipitation_amount',
     'dataset_name': 'nasa-imerg-late_global_0.1deg_1dy',
     },
    {'number': 27, 'name': 'NDVI MODIS-Afghanistan',
     'description': 'NDVI MODIS Afghanistan description',
     'size': [6631, 4144],
     'directory': '/data/data2/image/processed/eMODIS/ndvi-afghanistan/np/',
     'fillValue': -9999.,
     'indexer': dit.EveryFiveDaysIndex(),
     'inputDataLocation': get_dataLocation("centralasia"),
     'data_category': 'NDVI',
     },
    {'number': 28, 'name': 'NDVI MODIS-Asia',
     'description': 'NDVI MODIS Asia description',
     'size': [17407, 13676],
     'directory': '/data/data2/image/processed/eMODIS/ndvi-asia/np/',
     'fillValue': -9999.,
     'indexer': dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("centralasia"),
     'data_category': 'NDVI',
     'variable': 'ndvi',
     'dataset_name': 'emodis-ndvi_centralasia_250m_10dy',
     },
    {'number': 29,
     'name': 'ESI', 'description': 'Global ESI  Dataset ',
     'size': [7200, 3000],
     'directory': '/data/data3/image/processed/esi/4WK/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex("P8D"),  # dit.EveryEightDaysIndex(),
     'inputDataLocation': get_dataLocation("sport-esi/4wk"),
     'data_category': 'ESI',
     'variable': 'esi',
     'dataset_name': 'sport-esi_global_0.05deg_4wk',
     },
    # There will be more added here in time.
    {'number': 30,
     'name': 'dummy',
     'size': [7200, 3000],

     },
    {'number': 31,
     'name': 'Chirps-GEFS-Anom', 'description': 'Global CHIRPS GEFS Anomalies Dataset ',
     'size': [7200, 2000],
     'directory': '/data/data3/image/processed/gefs_anom/',
     'fillValue': -9999.,
     'indexer': dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("ucsb-chirps-gefs"),
     'data_category': 'CHIRPS',
     'variable': 'precipitation_anomaly',
     'dataset_name': 'ucsb-chirps-gefs_global_0.05deg_10dy',
     },
    {'number': 32,
     'name': 'Chirps-GEFS-Precip', 'description': 'Global CHIRPS GEFS Precipitation Dataset ',
     'size': [7200, 2000],
     'directory': '/cserv2/tmp/gefs_precip/',
     'fillValue': -9999.,
     'indexer': dit.DailyIndex(),  # dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("ucsb-chirps-gefs"),
     'data_category': 'CHIRPS',
     'variable': 'precipitation_amount',
     'dataset_name': 'ucsb-chirps-gefs_global_0.05deg_10dy',
     },
    # There will be more added here in time.
    {'number': 33,
     'name': 'ESI', 'description': 'Global ESI  Dataset ',
     'size': [7200, 3000],
     'directory': '/data/data3/image/processed/esi/12WK/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex("P8D"),  # dit.EveryEightDaysIndex(),
     'inputDataLocation': get_dataLocation("sport-esi/12wk"),
     'data_category': 'ESI',
     'variable': 'esi',
     'dataset_name': 'sport-esi_global_0.05deg_12wk',
     },
    {'number': 34,
     'name': 'IMERG Test',
     'description': 'GPM IMERG Daily Accumulation Precip',
     'size': [3600, 1800],
     'directory': '/data/data2/image/processed/IMERGTest/',
     'fillValue': 9999.,
     'indexer': dit.DynamicIndex("P1D"),
     'inputDataLocation': get_dataLocation("nasa-imerg-late"),
     'data_category': 'IMERG'
     },
    {'number': 35,
     'name': 'Chirps-GEFS-Precip', 'description': 'Global CHIRPS GEFS 25th Percentile Dataset ',
     'size': [7200, 2000],
     'directory': '/data/data3/image/processed/gefs_precip_25/',
     'fillValue': -9999.,
     'indexer': dit.DailyIndex(),  # dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("ucsb-chirps-gefs"),
     'data_category': 'CHIRPS',
     'variable': 'precipitation_amount',
     'dataset_name': 'ucsb-chirps-gefs_global_0.05deg_10dy',
     },
    {'number': 36,
     'name': 'Chirps-GEFS-Precip', 'description': 'Global CHIRPS GEFS 75th Percentile Dataset ',
     'size': [7200, 2000],
     'directory': '/data/data3/image/processed/gefs_precip_75/',
     'fillValue': -9999.,
     'indexer': dit.DailyIndex(),  # dit.DecadalIndex(),
     'inputDataLocation': get_dataLocation("ucsb-chirps-gefs"),
     'data_category': 'CHIRPS'
     },
    {'number': 37,
     'name': 'USDA SMAP', 'description': 'USDA SMAP Dataset 10KM',
     'size': [964, 406],
     'directory': '/cserv2/tmp/usda_smap/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex('P3D'),
     'inputDataLocation': get_dataLocation("usda-smap"),
     'data_category': 'SMAP',
     'variable': 'smp',
     'dataset_name': 'usda-smap_global_10km_3dy',
     },
    {'number': 38,
     'name': 'USDA SMAP', 'description': 'USDA SMAP Dataset 10KM',
     'size': [964, 406],
     'directory': '/cserv2/tmp/usda_smap/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex('P3D'),
     'inputDataLocation': get_dataLocation("usda-smap"),
     'data_category': 'SMAP',
     'variable': 'ssm',
     'dataset_name': 'usda-smap_global_10km_3dy',
     },
    {'number': 39,
     'name': 'USDA SMAP', 'description': 'USDA SMAP Dataset 10KM',
     'size': [964, 406],
     'directory': '/cserv2/tmp/usda_smap/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex('P3D'),
     'inputDataLocation': get_dataLocation("usda-smap"),
     'data_category': 'SMAP',
     'variable': 'ssma',
     'dataset_name': 'usda-smap_global_10km_3dy',
     },
    {'number': 40,
     'name': 'USDA SMAP', 'description': 'USDA SMAP Dataset 10KM',
     'size': [964, 406],
     'directory': '/cserv2/tmp/usda_smap/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex('P3D'),
     'inputDataLocation': get_dataLocation("usda-smap"),
     'data_category': 'SMAP',
     'variable': 'susm',
     'dataset_name': 'usda-smap_global_10km_3dy',
     },
    {'number': 41,
     'name': 'USDA SMAP', 'description': 'USDA SMAP Dataset 10KM',
     'size': [964, 406],
     'directory': '/cserv2/tmp/usda_smap/',
     'fillValue': -9999.,
     'indexer': dit.DynamicIndex('P3D'),
     'inputDataLocation': get_dataLocation("usda-smap"),
     'data_category': 'SMAP',
     'variable': 'susma',
     'dataset_name': 'usda-smap_global_10km_3dy',
     },
    # cfsv2 data
    {
        'number': 42,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens01',
        'ensemble_Label': 'ensemble 01', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens01 Temperature',
        'description': 'Climate Change Scenario: ens01 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens001'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens001',
    },
    {
        'number': 43,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens01',
        'ensemble_Label': 'Ensemble 01', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens01 Precipitation',
        'description': 'Climate Change Scenario: ens01 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens001'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens001',
    },
    {
        'number': 44,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens02',
        'ensemble_Label': 'ensemble 02', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens02 Temperature',
        'description': 'Climate Change Scenario: ens02 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens002'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens002',
    },
    {
        'number': 45,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens02',
        'ensemble_Label': 'Ensemble 02', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens02 Precipitation',
        'description': 'Climate Change Scenario: ens02 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens002'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens002',
    },
    {
        'number': 46,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens03',
        'ensemble_Label': 'ensemble 03', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens03 Temperature',
        'description': 'Climate Change Scenario: ens03 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens003'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens003',
    },
    {
        'number': 47,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens03',
        'ensemble_Label': 'Ensemble 03', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens03 Precipitation',
        'description': 'Climate Change Scenario: ens03 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens003'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens003',
    },
    {
        'number': 48,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens04',
        'ensemble_Label': 'ensemble 04', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens04 Temperature',
        'description': 'Climate Change Scenario: ens04 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens004'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens004',
    },
    {
        'number': 49,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens04',
        'ensemble_Label': 'Ensemble 04', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens04 Precipitation',
        'description': 'Climate Change Scenario: ens04 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens004'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens004',
    },
    {
        'number': 50,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens05',
        'ensemble_Label': 'ensemble 05', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens05 Temperature',
        'description': 'Climate Change Scenario: ens05 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens005'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens005',
    },
    {
        'number': 51,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens05',
        'ensemble_Label': 'Ensemble 05', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens05 Precipitation',
        'description': 'Climate Change Scenario: ens05 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens005'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens005',
    },
    {
        'number': 52,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens06',
        'ensemble_Label': 'ensemble 06', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens06 Temperature',
        'description': 'Climate Change Scenario: ens06 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens006'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens006',
    },
    {
        'number': 53,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens06',
        'ensemble_Label': 'Ensemble 06', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens06 Precipitation',
        'description': 'Climate Change Scenario: ens06 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens006'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens006',
    },
    {
        'number': 54,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens07',
        'ensemble_Label': 'ensemble 07', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens07 Temperature',
        'description': 'Climate Change Scenario: ens07 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens007'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens007',
    },
    {
        'number': 55,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens07',
        'ensemble_Label': 'Ensemble 07', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens07 Precipitation',
        'description': 'Climate Change Scenario: ens07 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens007'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens007',
    },
    {
        'number': 56,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens08',
        'ensemble_Label': 'ensemble 08', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens08 Temperature',
        'description': 'Climate Change Scenario: ens08 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens008'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens008',
    },
    {
        'number': 57,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens08',
        'ensemble_Label': 'Ensemble 08', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens08 Precipitation',
        'description': 'Climate Change Scenario: ens08 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens008'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens008',
    },
    {
        'number': 58,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens09',
        'ensemble_Label': 'ensemble 09', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens10 Temperature',
        'description': 'Climate Change Scenario: ens10 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens009'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens009',
    },
    {
        'number': 59,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens09',
        'ensemble_Label': 'Ensemble 09', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens01 Precipitation',
        'description': 'Climate Change Scenario: ens10 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens009'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens009',
    },
    {
        'number': 60,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens10',
        'ensemble_Label': 'ensemble 10', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens10 Temperature',
        'description': 'Climate Change Scenario: ens10 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens010'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens010',
    },
    {
        'number': 61,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens10',
        'ensemble_Label': 'Ensemble 10', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens10 Precipitation',
        'description': 'Climate Change Scenario: ens10 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens010'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens010',
    },
    {
        'number': 62,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens11',
        'ensemble_Label': 'ensemble 11', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens11 Temperature',
        'description': 'Climate Change Scenario: ens11 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens011'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens011',
    },
    {
        'number': 63,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens11',
        'ensemble_Label': 'Ensemble 11', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens11 Precipitation',
        'description': 'Climate Change Scenario: ens11 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens011'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens011',
    },
    {
        'number': 64,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens12',
        'ensemble_Label': 'ensemble 12', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens12 Temperature',
        'description': 'Climate Change Scenario: ens12 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens012'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens012',
    },
    {
        'number': 65,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens12',
        'ensemble_Label': 'Ensemble 12', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens12 Precipitation',
        'description': 'Climate Change Scenario: ens12 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens012'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens012',
    },
    {
        'number': 66,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens13',
        'ensemble_Label': 'ensemble 13', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens13 Temperature',
        'description': 'Climate Change Scenario: ens13 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens013'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens013',
    },
    {
        'number': 67,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens13',
        'ensemble_Label': 'Ensemble 13', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens13 Precipitation',
        'description': 'Climate Change Scenario: ens13 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens013'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens013',
    },
    {
        'number': 68,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens14',
        'ensemble_Label': 'ensemble 14', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens14 Temperature',
        'description': 'Climate Change Scenario: ens14 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens014'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens014',
    },
    {
        'number': 69,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens14',
        'ensemble_Label': 'Ensemble 14', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens14 Precipitation',
        'description': 'Climate Change Scenario: ens14 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens014'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens014',
    },
    {
        'number': 70,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens15',
        'ensemble_Label': 'ensemble 15', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens15 Temperature',
        'description': 'Climate Change Scenario: ens15 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens015'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens015',
    },
    {
        'number': 71,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens15',
        'ensemble_Label': 'Ensemble 15', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens15 Precipitation',
        'description': 'Climate Change Scenario: ens15 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens015'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens015',
    },
    {
        'number': 72,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens16',
        'ensemble_Label': 'ensemble 16', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens16 Temperature',
        'description': 'Climate Change Scenario: ens16 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens016'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens016',
    },
    {
        'number': 73,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens16',
        'ensemble_Label': 'Ensemble 16', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens16 Precipitation',
        'description': 'Climate Change Scenario: ens16 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens016'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens016',
    },
    {
        'number': 74,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens17',
        'ensemble_Label': 'ensemble 17', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens17 Temperature',
        'description': 'Climate Change Scenario: ens17 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens017'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens017',
    },
    {
        'number': 75,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens17',
        'ensemble_Label': 'Ensemble 17', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens17 Precipitation',
        'description': 'Climate Change Scenario: ens17 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens017'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens017',
    },
    {
        'number': 76,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens18',
        'ensemble_Label': 'ensemble 18', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens18 Temperature',
        'description': 'Climate Change Scenario: ens18 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens018'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens018',
    },
    {
        'number': 77,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens18',
        'ensemble_Label': 'Ensemble 18', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens18 Precipitation',
        'description': 'Climate Change Scenario: ens18 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens018'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens018',
    },
    {
        'number': 78,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens19',
        'ensemble_Label': 'ensemble 19', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens19 Temperature',
        'description': 'Climate Change Scenario: ens19 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens019'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens019',
    },
    {
        'number': 79,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens19',
        'ensemble_Label': 'Ensemble 19', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens19 Precipitation',
        'description': 'Climate Change Scenario: ens19 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens019'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens019',
    },
    {
        'number': 80,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens20',
        'ensemble_Label': 'ensemble 20', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens20 Temperature',
        'description': 'Climate Change Scenario: ens20 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens020'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens020',
    },
    {
        'number': 81,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens20',
        'ensemble_Label': 'Ensemble 20', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens20 Precipitation',
        'description': 'Climate Change Scenario: ens20 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens020'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens020',
    },
    {
        'number': 82,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens21',
        'ensemble_Label': 'ensemble 21', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens21 Temperature',
        'description': 'Climate Change Scenario: ens21 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens021'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens021',
    },
    {
        'number': 83,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens21',
        'ensemble_Label': 'Ensemble 21', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens21 Precipitation',
        'description': 'Climate Change Scenario: ens21 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens021'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens021',
    },
    {
        'number': 84,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens22',
        'ensemble_Label': 'ensemble 22', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens22 Temperature',
        'description': 'Climate Change Scenario: ens22 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens022'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens022',
    },
    {
        'number': 85,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens22',
        'ensemble_Label': 'Ensemble 22', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens22 Precipitation',
        'description': 'Climate Change Scenario: ens22 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens022'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens022',
    },
    {
        'number': 86,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens23',
        'ensemble_Label': 'ensemble 23', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens23 Temperature',
        'description': 'Climate Change Scenario: ens23 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens023'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens023',
    },
    {
        'number': 87,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens23',
        'ensemble_Label': 'Ensemble 23', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens23 Precipitation',
        'description': 'Climate Change Scenario: ens23 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens023'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens023',
    },
    {
        'number': 88,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens24',
        'ensemble_Label': 'ensemble 24', 'variable_Label': 'Temperature',
        'name': 'Climate Change Scenario: ens24 Temperature',
        'description': 'Climate Change Scenario: ens24 Temperature',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens024'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'air_temperature',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens024',
    },
    {
        'number': 89,
        'data_category': 'ClimateModel',
        'ensemble': 'cfsv2_ens24',
        'ensemble_Label': 'Ensemble 24', 'variable_Label': 'Precipitation',
        'name': 'Climate Change Scenario: ens24 Precipitation',
        'description': 'Climate Change Scenario: ens24 Precipitation',
        'inputDataLocation': get_ClimateChangeParam__inputDataLocation_cfsv2('ens024'),
        'size': get_ClimateChangeParam__size(), 'fillValue': get_ClimateChangeParam__fillValue(),
        'indexer': get_ClimateChangeParam__indexer(),
        'number_Of_ForecastDays': get_ClimateChangeParam__number_Of_ForecastDays(),
        'variable': 'precipitation',
        'dataset_name': 'nmme-cfsv2_bcsd.latest.global.0.5deg.daily.ens024',
    },
    {'number': 90,
     'name': 'Chirp', 'description': 'CHIRP Dataset ',
     'size': [7200, 2000],
     'directory': '/cserv2/tmp/chirp/',
     'fillValue': -9999.,
     'indexer': dit.DailyIndex(),
     'inputDataLocation': get_dataLocation("ucsb-chirp"),
     'data_category': 'CHIRP',
     'variable': 'precipitation_amount',
     'dataset_name': 'ucsb-chirp_global_0.05deg_daily',
     },
    {'number': 91,
     'name': 'IMERG 1 Day',
     'description': 'GPM IMERG Daily Accumulation Precip',
     'size': [3600, 1800],
     'directory': '/data/data2/image/processed/IMERG1Day/',
     'fillValue': 9999.,
     'indexer': dit.DynamicIndex("P1D"),
     'inputDataLocation': get_dataLocation("nasa-imerg-early"),
     'data_category': 'IMERG',
     'variable': 'precipitation_amount',
     'dataset_name': 'nasa-imerg-early_global_0.1deg_1dy',
     },
]
dataTypeInfo = [{'path': '/cserv2/tmp/mapfiles', 'layer': 'county'}]
shapefileName = [{'id': 'country',
                  'displayName': "Countries",
                  'shapefilename': 'country.shp',
                  'visible': 'true'},
                 {'id': 'admin_1_earth',
                  'displayName': "Admin #1",
                  'shapefilename': 'admin_1_earth.shp',
                  'visible': 'false'},
                 {'id': 'admin_2_af',
                  'displayName': "Admin #2",
                  'shapefilename': 'admin_2_af.shp',
                  'visible': 'false'},
                 {'id': 'sept2015_zoi',
                  'displayName': "FTF ZOI",
                  'shapefilename': 'sept2015_zoi.shp',
                  'visible': 'false'}
                 ]
operationTypes = [
    [0, 'max', "Max"],
    [1, 'min', "Min"],
    [2, 'median', "Median"],
    [3, 'range', "Range"],
    [4, 'sum', "Sum"],
    [5, 'avg', "Average"],
    [6, 'getraw', "GetRawData"]
]
intervals = [
    {'name': 'day', 'pattern': '%m/%d/%Y'},
    {'name': 'month', 'pattern': '%m/%Y'},
    {'name': 'year', 'pattern': '%Y'}
]

resultsdir = '''/mnt/cs-temp/request_out/'''  # '''/cserv2/tmp/'''
