name: climateserv2
dependencies:
- cdo=1.9.10
- click=8.0.1
- gdal=3.3.1
- geoip2=4.0.2
- geos=3.9.1
- geotiff=1.6.0
- gunicorn=20.1.0
- hdf4=4.2.15
- hdf5=1.10.6
- libgdal=3.3.1
- libnetcdf=4.8.0
- maxminddb=2.0.2
- netcdf4=1.5.7
- numpy=1.21.1
- pillow=8.3.1
- python-dateutil=2.8.2
- pytz=2021.1
- pyparsing=2.4.7
- six=1.16.0
- xarray=0.19.0
- dask=2021.8.1
- pip
- pip:
    - affine==2.3.0
    - asgiref==3.3.4
    - attrs==21.2.0
    - boto3==1.18.54
    - bs4==0.0.1
    - celery==5.2.7
    - certifi==2021.5.30
    - chardet==4.0.0
    - click-plugins==1.1.1
    - cligj==0.7.2
    - django==3.2.15
    - django-extensions==3.1.3
    - djangorestframework==3.12.4
    - djangorestframework-simplejwt==4.7.1
    - geopandas==0.9.0
    - h5py==3.3.0
    - idna==2.10
    - pandas==1.2.5
    - psycopg2==2.9.1
    - pyproj==3.1.0
    - pytz==2021.1
    - rasterio==1.2.6
    - requests==2.25.1
    - rioxarray==0.6.1
    - scipy==1.7.0
    - shapely==1.7.1
    - snuggs==1.4.7
    - urllib3==1.26.6
    - wget==3.2