# Generated by Django 3.2.4 on 2021-06-24 02:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setting_name', models.CharField(default='UNKNOWN_SETTING', help_text='What is the name of this setting.  These are meant to be unique but not constrained by the database.  If there are any settings with the exact same name, please delete the duplicates.', max_length=250, verbose_name='Setting Name')),
                ('setting_value', models.TextField(default='{}', help_text='Setting Value.  Can be a string, or JSON Object, etc.  If this value is just a string or number only, remove the {} default.', verbose_name='Setting Value')),
                ('setting_data_type', models.CharField(default='STRING', help_text="Setting Datatype.  This is important.  Choices are: 'STRING', 'LIST', 'JSON'.  If the datatype is not recognized, then STRING is used.  Note: JSON types are loaded with json.loads(<value>).  Note: LIST types are read as comma separated strings.  Something like '1,2,3' would get converted into ['1','2','3'] to be used in the code.  List Items have to be strings, not numbers, and not complex objects.  List Item Type conversion and validation happens at the code where it is needed.", max_length=250, verbose_name='Setting Data Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='ETL_Dataset',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(default='Unknown Dataset Name', help_text='A Human Readable Custom Name to identify this dataset.  Typically expected usage would be for Admin to set this name so they can quickly understand which data set they are looking at.  They could also use the other TDS fields to understand exactly which dataset this refers to.', max_length=90, verbose_name='Human Readable Dataset Short Name')),
                ('dataset_subtype', models.CharField(default='Unknown_Dataset_Subtype', help_text='IMPORTANT: This setting is used by the pipeline to select which specific sub type script logic gets used to execute the ETL job.  There are a set list of Subtypes, use python manage.py list_etl_dataset_subtypes to see a list of all subtypes.', max_length=90, verbose_name='Dataset Subtype')),
                ('is_pipeline_enabled', models.BooleanField(default=False, help_text="Is this ETL Dataset currently set to 'enabled' for ETL Pipeline processing?  If this is set to False, then when the ETL job runs to process this incoming data, the ETL pipeline for this process will be stopped before it makes an attempt.  This is intended as a way for admin to just 'turn off' or 'turn on' a specific ETL job that has been setup.")),
                ('is_pipeline_active', models.BooleanField(default=False, help_text='Is this ETL Dataset currently being run through the ETL Pipeline? If this is set to True, that means an ETL job is actually running for this specific dataset and data ingestion is currently in progress.  When a pipeline finishes (success or error) this value should be set to False by the pipeline code.')),
                ('capabilities', models.TextField(default='{}', help_text="Set Automatically by ETL Pipeline.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.  This is a field to hold Dataset specific information that the clientside code may need access to in order to properly render the details from this dataset.  (In ClimateSERV 1.0, some of this was a GeoReference, Time/Date Ranges, and other information.)", verbose_name='JSON Data')),
                ('tds_product_name', models.CharField(default='UNKNOWN_PRODUCT_NAME', help_text="The Product name as defined on the THREDDS Data Server (TDS) Conventions Document.  Example Value: 'EMODIS-NDVI'", max_length=90, verbose_name='(TDS Conventions) Product Name')),
                ('tds_region', models.CharField(default='UNKNOWN_REGION', help_text="The Region as defined on the THREDDS Data Server (TDS) Conventions Document.  Example Value: 'Global'", max_length=90, verbose_name='(TDS Conventions) Region')),
                ('tds_spatial_resolution', models.CharField(default='UNKNOWN_SPATIAL_RESOLUTION', help_text="The Spatial Resolution as defined on the THREDDS Data Server (TDS) Conventions Document.  Example Value: '250m'", max_length=90, verbose_name='(TDS Conventions) Spatial Resolution')),
                ('tds_temporal_resolution', models.CharField(default='UNKNOWN_TEMPORAL_RESOLUTION', help_text="The Temporal Resolution as defined on the THREDDS Data Server (TDS) Conventions Document.  Example Value: '2mon'", max_length=90, verbose_name='(TDS Conventions) Temporal Resolution')),
                ('dataset_legacy_datatype', models.CharField(default='9999', help_text="The 'datatype' number from ClimateSERV 1.0.  This is mapped in support of Legacy API Requests", max_length=5, verbose_name='Legacy datatype')),
                ('dataset_nc4_variable_name', models.CharField(default='ndvi', help_text='To select data from an NC4 file requires a variable name.  This is the field where a variable name must be set for the selection from NC4 file to work properly.', max_length=40, verbose_name='Variable Name inside NC4 File')),
                ('is_lat_order_reversed', models.BooleanField(default=False, help_text='Some datasets have their lat order reversed.  The downstream affect of this has to do with NC4 data selection.  If this flag is set to True then we use, latitude=slice(max_Lat, min_Lat), if it is set to false, then the selection uses latitude=slice(min_Lat, max_Lat) - Note, at the time of this writing, NDVI types should be set to False')),
                ('dataset_base_directory_path', models.CharField(default='UNSET', help_text='This is a field that tells the job processing code where to look to find ALL of the NetCDF files (NC4 files) for this dataset.  In many cases (at this time all cases) this is the same as the setting for the THREDDS output directory. This is an absolute path which means the directory path should begin with /.  The code that uses this also expects a / at the end of the directory name.', max_length=255, verbose_name='Base Directory Path')),
                ('additional_json', models.TextField(default='{}', help_text="Extra data field.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.", verbose_name='JSON Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.CharField(default='Table_Default_Process', help_text='Who or What Process created this record? 90 chars max', max_length=90, verbose_name='Created By User or Process Name or ID')),
                ('is_test_object', models.BooleanField(default=False, help_text='Is this Instance meant to be used ONLY for internal platform testing? (Used only for easy cleanup - DO NOT DEPEND ON FOR VALIDATION)')),
            ],
        ),
        migrations.CreateModel(
            name='ETL_Granule',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('granule_name', models.CharField(default='Unknown Granule Name', help_text="Most of the time, this may be a filename.  Sometimes it is not.  It should be a name that is unique to the combination of dataset and temporal data value.  This row should be useful in tracking down the specific granule's file/source info.", max_length=250, verbose_name='Granule Name')),
                ('granule_contextual_information', models.TextField(default='No Additional Information', help_text='A way to capture additional contextual information around a granule, if needed.', verbose_name='Granule Contextual Information')),
                ('is_missing', models.BooleanField(default=False, help_text='Was this expected granule missing at the time of processing?  If this is set to True, that means during an ingest run, there was an expected granule that was either not found at the data source, or had an error that made it unable to be processed and ingested.  The time that this record gets created as compared to ETL Log rows would be a good way to nail down the exact issue as more data is stored about issues in the ETL Log table.')),
                ('granule_pipeline_state', models.CharField(default='UNSET_ATTEMPTED', help_text='Each Individual Granule has a pipeline state.  This lets us easily understand if the Granule succeeded or failed', max_length=20, verbose_name='Granule Pipeline State')),
                ('additional_json', models.TextField(default='{}', help_text="Extra data field.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.", verbose_name='JSON Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.CharField(default='Table_Default_Process', help_text='Who or What Process created this record? 90 chars max', max_length=90, verbose_name='Created By User or Process Name or ID')),
                ('is_test_object', models.BooleanField(default=False, help_text='Is this Instance meant to be used ONLY for internal platform testing? (Used only for easy cleanup - DO NOT DEPEND ON FOR VALIDATION)')),
                ('etl_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ETL_PipelineRun',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.CharField(default='Table_Default_Process', help_text='Who or What Process created this record? 90 chars max', max_length=90, verbose_name='Created By User or Process Name or ID')),
                ('additional_json', models.TextField(default='{}', help_text="Extra data field.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.", verbose_name='JSON Data')),
                ('is_test_object', models.BooleanField(default=False, help_text='Is this Instance meant to be used ONLY for internal platform testing? (Used only for easy cleanup - DO NOT DEPEND ON FOR VALIDATION)')),
            ],
        ),
        migrations.CreateModel(
            name='ETL_Log',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('activity_event_type', models.CharField(default='Unknown ETL Activity Event Type', help_text='What is the standardized type for this ETL Activity Event?', max_length=90, verbose_name='Standardized Activity Event Type')),
                ('activity_description', models.TextField(default='No Description', help_text='A field for more detailed information on an ETL Event Activity', verbose_name='Activity Description')),
                ('is_alert', models.BooleanField(default=False, help_text='Is this an Item that should be considered an alert?  (by default, all errors and warnings are considered alerts)')),
                ('is_alert_dismissed', models.BooleanField(default=False, help_text='Setting this to True will change the display style for the admin.')),
                ('additional_json', models.TextField(default='{}', help_text="Extra data field.  Please don't touch this!  Messing with this will likely result in broken content elsewhere in the system.", verbose_name='JSON Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.CharField(default='Table_Default_Process', help_text='Who or What Process created this record? 90 chars max', max_length=90, verbose_name='Created By User or Process Name or ID')),
                ('is_test_object', models.BooleanField(default=False, help_text='Is this Instance meant to be used ONLY for internal platform testing? (Used only for easy cleanup - DO NOT DEPEND ON FOR VALIDATION)')),
                ('etl_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_dataset')),
                ('etl_granule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_granule')),
                ('etl_pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_pipelinerun')),
            ],
        ),
        migrations.AddField(
            model_name='etl_granule',
            name='etl_pipeline_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_pipelinerun'),
        ),
    ]
