# Generated by Django 3.2.6 on 2022-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl_log',
            name='activity_event_type',
            field=models.TextField(default='Unknown ETL Activity Event Type', help_text='What is the standardized type for this ETL Activity Event?', verbose_name='Standardized Activity Event Type'),
        ),
    ]
