# Generated by Django 3.2.4 on 2021-07-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config_setting',
            options={'ordering': ['setting_name'], 'verbose_name': 'Config Setting', 'verbose_name_plural': 'Config Settings'},
        ),
        migrations.AlterModelOptions(
            name='etl_dataset',
            options={'verbose_name': 'ETL Dataset', 'verbose_name_plural': 'ETL Datasets'},
        ),
        migrations.AlterModelOptions(
            name='etl_granule',
            options={'verbose_name': 'ETL Granule', 'verbose_name_plural': 'ETL Granules'},
        ),
        migrations.AlterModelOptions(
            name='etl_log',
            options={'verbose_name': 'ETL Log', 'verbose_name_plural': 'ETL Logs'},
        ),
        migrations.AlterModelOptions(
            name='etl_pipelinerun',
            options={'verbose_name': 'ETL Pipeline Run', 'verbose_name_plural': 'ETL Pipeline Runs'},
        ),
        migrations.AlterField(
            model_name='etl_granule',
            name='etl_dataset',
            field=models.ForeignKey(blank=True, help_text='Each Individual Granule has a parent ETL Dataset, storing the association here', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_dataset'),
        ),
        migrations.AlterField(
            model_name='etl_granule',
            name='etl_pipeline_run',
            field=models.ForeignKey(blank=True, help_text='Each time the ETL Pipeline runs, there is a unique ID generated, this field operates like a way to tag which pipeline this row is attached to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_pipelinerun'),
        ),
        migrations.AlterField(
            model_name='etl_log',
            name='etl_dataset',
            field=models.ForeignKey(blank=True, help_text='If there is an associated ETL Dataset UUID, it should appear here.  Note: This field may be blank or unset, not all events will have one of these associated items.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_dataset'),
        ),
        migrations.AlterField(
            model_name='etl_log',
            name='etl_granule',
            field=models.ForeignKey(blank=True, help_text='If there is an associated ETL Granule UUID, it should appear here.  Note: This field may be blank or unset, not all events will have one of these associated items.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_granule'),
        ),
        migrations.AlterField(
            model_name='etl_log',
            name='etl_pipeline_run',
            field=models.ForeignKey(blank=True, help_text='Each time the ETL Pipeline runs, there is a unique ID generated, this field operates like a way to tag which pipeline this row is attached to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etl_pipelinerun'),
        ),
    ]
