# Generated by Django 3.2.6 on 2022-01-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50)),
                ('API_request_txt_files', models.CharField(default=None, max_length=50)),
                ('API_request_zip_files', models.CharField(default=None, max_length=50)),
                ('ingested_datasets', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='track_usage',
            options={'ordering': ['-time_requested'], 'verbose_name': 'Usage Record', 'verbose_name_plural': 'Usage Records'},
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='end_day',
            field=models.CharField(default='30', max_length=2),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='end_month',
            field=models.CharField(default='12', max_length=2),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='end_year',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='start_day',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='start_month',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='start_year',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='country_ISO',
            field=models.CharField(help_text='ISO Country Code for originating IP', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='metadata_request',
            field=models.BooleanField(default=False, help_text='Is this a request for metadata instead of actual data (eg., information about what data is available)?', null=True),
        ),
        migrations.AlterField(
            model_name='track_usage',
            name='ui_request',
            field=models.BooleanField(default=False, help_text='Is this request originated through the CS UI?'),
        ),
    ]
