# Generated by Django 3.2.6 on 2022-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track_usage',
            options={'ordering': ['-time_requested'], 'verbose_name': 'Usage Record', 'verbose_name_plural': 'Usage Records'},
        ),
        migrations.AddField(
            model_name='track_usage',
            name='country_ISO',
            field=models.CharField(help_text='ISO Country Code for originating IP', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='metadata_request',
            field=models.BooleanField(default=False, help_text='Is this a request for metadata instead of actual data (eg., information about what data is available)?', null=True),
        ),
        migrations.AlterField(
            model_name='track_usage',
            name='ui_request',
            field=models.BooleanField(default=False, help_text='Is this request originated through the CS UI?'),
        ),
    ]
