# Generated by Django 3.2.6 on 2021-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50)),
                ('log', models.JSONField()),
                ('log_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=50)),
            ],
        ),
    ]
