# Generated by Django 3.2.6 on 2021-12-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track_usage',
            name='task_ID',
        ),
    ]
