# Generated by Django 3.2.6 on 2021-12-27 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_track_usage_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track_usage',
            name='task_ID',
        ),
        migrations.AddField(
            model_name='track_usage',
            name='API_call',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='calculation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='data_retrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='progress',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='ui_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='temp_working_dir',
            field=models.TextField(default='', help_text='The local filesystem place to store data', verbose_name='(Path) Local temp working directory'),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etl_pipelinerun',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
    ]
