# Generated by Django 3.2.6 on 2021-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request_log_request_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_log',
            name='log_dat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
