# Generated by Django 3.2.6 on 2021-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_track_usage_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_usage',
            name='API_call',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='data_retrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track_usage',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
