# Generated by Django 3.2.6 on 2022-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220109_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run_ETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(default='2020', max_length=4)),
                ('end_year', models.CharField(default='2020', max_length=4)),
                ('start_month', models.CharField(default='1', max_length=2)),
                ('end_month', models.CharField(default='12', max_length=2)),
                ('start_day', models.CharField(default='1', max_length=2)),
                ('end_day', models.CharField(default='30', max_length=2)),
            ],
            options={
                'verbose_name': 'Run ETL',
                'verbose_name_plural': 'Run ETLs',
            },
        ),
    ]
