# Generated by Django 3.2.4 on 2021-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210705_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl_dataset',
            name='final_load_dir',
            field=models.TextField(default='', help_text='The local filesystem place to store the final NC4 files (The THREDDS monitored Directory location)', verbose_name='(Path)'),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='source_url',
            field=models.TextField(default='', help_text='The remote location', verbose_name='(URL) Remote location'),
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='temp_working_dir',
            field=models.TextField(default='', help_text='The local filesystem place to store data', verbose_name='(Path) Temp working direcory'),
        ),
    ]
