# Generated by Django 3.2.6 on 2022-01-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_run_etl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run_etl',
            options={'verbose_name': 'ETL Run', 'verbose_name_plural': 'ETL runs'},
        ),
        migrations.AddField(
            model_name='run_etl',
            name='etl',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=60),
        ),
        migrations.AddField(
            model_name='run_etl',
            name='from_last_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run_etl',
            name='merge_option',
            field=models.CharField(choices=[('no_merge', 'no_merge'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='never', max_length=10),
        ),
    ]
