# Generated by Django 3.2.6 on 2021-11-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request_log_log_dat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50)),
                ('originating_IP', models.CharField(max_length=50)),
                ('task_ID', models.CharField(max_length=50)),
                ('time_requested', models.DateTimeField()),
                ('AOI', models.JSONField()),
                ('dataset', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('request_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
            ],
        ),
    ]
