# Generated by Django 3.2.6 on 2022-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etl_dataset_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etl_dataset',
            name='start_date',
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='end_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='end_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='start_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='start_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
