# Generated by Django 3.2.6 on 2021-12-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211209_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_usage',
            name='AOI',
            field=models.JSONField(null=True),
        ),
    ]
