# Generated by Django 3.2.6 on 2021-09-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210803_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etl_dataset',
            options={'ordering': ['dataset_name'], 'verbose_name': 'ETL Dataset', 'verbose_name_plural': 'ETL Datasets'},
        ),
        migrations.AlterModelOptions(
            name='etl_granule',
            options={'ordering': ['-created_at'], 'verbose_name': 'ETL Granule', 'verbose_name_plural': 'ETL Granules'},
        ),
        migrations.AlterModelOptions(
            name='etl_log',
            options={'ordering': ['-created_at'], 'verbose_name': 'ETL Log', 'verbose_name_plural': 'ETL Logs'},
        ),
        migrations.AlterModelOptions(
            name='etl_pipelinerun',
            options={'ordering': ['-created_at'], 'verbose_name': 'ETL Pipeline Run', 'verbose_name_plural': 'ETL Pipeline Runs'},
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='final_load_dir',
            field=models.TextField(default='', help_text='The local filesystem place to store the final NC4 files (The THREDDS monitored Directory location)', verbose_name='(Path) Local NC4 directory'),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='temp_working_dir',
            field=models.TextField(default='', help_text='The local filesystem place to store data', verbose_name='(Path) Local temp working direcory'),
        ),
    ]
