# Generated by Django 3.2.6 on 2022-01-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220107_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl_dataset',
            name='end_month',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='end_year',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='start_month',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='start_year',
            field=models.TextField(),
        ),
    ]
