# Generated by Django 3.2.6 on 2022-01-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220111_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run_etl',
            name='etl',
            field=models.CharField(choices=[('1c3cf64c-940f-4d0a-aae3-75f05d8f6894', 'CHIRPS'), ('64048e53-991d-4eff-92ad-dd63b042f762', 'CHIRPS'), ('5c48d6d9-fc4c-4eee-8777-7c84cc31e4c2', 'EMODIS'), ('43e0caea-1b74-48ed-a430-087dc692ebe6', 'ESI 12WK'), ('3827321e-3471-4411-8b4a-c548867ce9b7', 'ESI 4WK'), ('0fc3927d-fdac-47f0-bdc2-eb343f5229df', 'IMERG EARLY - 1dy'), ('6dde5929-7d44-4f7e-819f-dd39e64e9697', 'IMERG EARLY - 30min'), ('276bc14f-6452-46ba-be5b-af23419a4dcf', 'IMERG LATE - 1dy'), ('d366cab9-8dd8-408e-8c67-b13ace3ff474', 'IMERG LATE - 30min'), ('c539318a-a3a8-4495-8c85-8d3b48d0bf62', 'NMME')], default='CHIRPS', max_length=60),
        ),
        migrations.AlterField(
            model_name='run_etl',
            name='merge_option',
            field=models.CharField(choices=[('no_merge', 'No Merge'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='never', max_length=10),
        ),
    ]
