# Generated by Django 3.2.6 on 2021-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_track_usage_aoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_usage',
            name='AOI',
            field=models.JSONField(default={}),
        ),
    ]
