# Generated by Django 3.2.6 on 2022-04-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220318_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEBUG_LIVE', models.BooleanField(default=False)),
                ('logToConsole', models.BooleanField(default=True)),
                ('pythonPath', models.CharField(default='/cserv2/python_environments/conda/anaconda3/envs/climateserv2/bin/python', max_length=255, verbose_name='Python Path')),
                ('serviringestroot', models.CharField(default='/cserv2/tmp/data/pythonCode/serviringest/', max_length=255, verbose_name='serviringestroot')),
                ('requestLog_db_basepath', models.CharField(default='/cserv2/tmp/', max_length=255, verbose_name='requestLog_db_basepath')),
                ('zipFile_ScratchWorkspace_Path', models.CharField(default='/mnt/cs-temp/request_out/', max_length=255, verbose_name='zipFile_ScratchWorkspace_Path')),
                ('logfilepath', models.CharField(default='/cserv2/tmp/', max_length=255, verbose_name='logfilepath')),
                ('workpath', models.CharField(default='/cserv2/tmp/', max_length=255, verbose_name='workpath')),
                ('shapefilepath', models.CharField(default='/cserv2/tmp/mapfiles/', max_length=255, verbose_name='shapefilepath')),
                ('ageInDaysToPurgeData', models.IntegerField(default=7)),
                ('nmme_ccsm4_path', models.CharField(default='/mnt/climateserv/nmme-ccsm4_bcsd/global/0.5deg/daily/latest/', max_length=255, verbose_name='nmme_ccsm4_path')),
                ('nmme_cfsv2_path', models.CharField(default='/mnt/climateserv/nmme-cfsv2_bcsd/global/0.5deg/daily/latest/', max_length=255, verbose_name='nmme_cfsv2_path')),
                ('base_data_path', models.CharField(default='/mnt/climateserv/', max_length=255, verbose_name='base_data_path')),
                ('resultsdir', models.CharField(default='/mnt/cs-temp/request_out/', max_length=255, verbose_name='base_data_path')),
                ('shapefileName', models.TextField(default='{}', verbose_name='JSON Data')),
            ],
        ),
    ]
