# Generated by Django 3.2.6 on 2022-01-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220109_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl_dataset',
            name='end_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='end_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='start_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='etl_dataset',
            name='start_year',
            field=models.CharField(max_length=4),
        ),
    ]
