# Generated by Django 3.2.6 on 2022-01-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220109_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl_dataset',
            name='end_day',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etl_dataset',
            name='start_day',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
