# Generated by Django 3.2.6 on 2022-01-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
