# Generated by Django 3.2.6 on 2021-12-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_track_usage_aoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_usage',
            name='AOI',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track_usage',
            name='progress',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
