# Generated by Django 3.2.6 on 2021-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211212_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_usage',
            name='calculation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
