# Generated by Django 3.2.6 on 2021-12-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_track_usage_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_usage',
            name='ui_request',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
