# Generated by Django 3.2.6 on 2022-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_etl_dataset_dataset_name_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='resultsdir',
            field=models.CharField(default='/mnt/cs-temp/request_out/', max_length=255, verbose_name='results dir'),
        ),
    ]
