# Generated by Django 3.2.6 on 2022-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_etl_dataset_fast_directory_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_usage',
            name='unique_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
