# Generated by Django 3.2.6 on 2022-07-13 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_track_usage_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_progress',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
