# Generated by Django 3.2.6 on 2022-07-13 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_request_progress_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_progress',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
