# Generated by Django 3.2.6 on 2022-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_request_progress_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_progress',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
