# Generated by Django 3.2.6 on 2022-07-22 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220722_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl_dataset_v2',
            name='filename_format_parameters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text="This field determines the parameters that are used to format the dataset's \n                                         stored filename (i.e. date, product type, region). The number of elements in \n                                         this array should be equal to the number of {} pairs in the pre-formatted \n                                         string.", size=None),
        ),
        migrations.AlterField(
            model_name='etl_dataset_v2',
            name='source_url_parameters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text="This field determines the parameters that are used to format the dataset's source \n                                    url with specified values (i.e. date, product type, region). The number of elements \n                                    in this array should be equal to the number of {} pairs in the pre-formatted string.", size=None),
        ),
    ]
