# Generated by Django 3.2.20 on 2024-10-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_wmsusage_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_usage',
            name='AOI',
            field=models.JSONField(default=None, null=True),
        ),
    ]
