# Generated by Django 3.2.6 on 2022-07-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220722_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl_dataset_v2',
            name='filename_format_string',
            field=models.CharField(blank=True, default='', help_text='This field specifies the string to be formatted that determines the full filename\n                                     when populated. Sections of the string that should be formatted should be \n                                     indicated with {} in this string.', max_length=100),
        ),
        migrations.AlterField(
            model_name='etl_dataset_v2',
            name='source_url_format_string',
            field=models.CharField(blank=True, default='', help_text='This field specifies the string to be formatted that determines the final url to \n                                       be searched. Sections of the string that should be formatted should be indicated \n                                       with {} in this string.', max_length=100),
        ),
    ]
