# Generated by Django 3.2.20 on 2024-12-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_track_usage_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_usage',
            name='API_call',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
