# Generated by Django 3.2.6 on 2022-08-02 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_etl_dataset_v2_nc4_attribute_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etl_dataset_v2',
            name='filename_format_parameters',
        ),
        migrations.RemoveField(
            model_name='etl_dataset_v2',
            name='is_test_object',
        ),
        migrations.RemoveField(
            model_name='etl_dataset_v2',
            name='source_url_format_string',
        ),
        migrations.RemoveField(
            model_name='etl_dataset_v2',
            name='source_url_parameters',
        ),
        migrations.AddField(
            model_name='etl_dataset_v2',
            name='filename_format_string_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', help_text='This field specifies the string to be formatted that determines the full filename\n                                          when populated. Sections of the string that should be formatted should be \n                                          indicated with {} in this string.', max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etl_dataset_v2',
            name='source_url_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='The remote location of the dataset resource', size=None),
        ),
    ]
