# Generated by Django 3.2.6 on 2022-08-02 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220802_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl_dataset_v2',
            name='filename_format_string_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', help_text='This field specifies the string to be formatted that determines the full filename\n                                          when populated. Sections of the string that should be formatted should be \n                                          indicated with {} in this string.', max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='etl_dataset_v2',
            name='source_url_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='The remote location of the dataset resource', size=None),
        ),
    ]
