# Generated by Django 3.2.6 on 2022-09-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_request_progress_date_created'),
        ('api', '0041_alter_etl_dataset_v2_contained_variables_list'),
    ]

    operations = [
    ]
