# Generated by Django 3.2.6 on 2022-01-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220112_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=True, max_length=127, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
