# Generated by Django 3.2.6 on 2022-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etl_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feedback_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
