# Generated by Django 3.2.6 on 2022-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220113_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default='', max_length=127, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='', max_length=127, unique=True),
            preserve_default=False,
        ),
    ]
