# Generated by Django 3.2.4 on 2021-07-09 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='Enter-Name', help_text='Enter a short name to identify the dataset', max_length=200)),
                ('heading', models.CharField(help_text='Enter heading to display on home page when featured', max_length=200)),
                ('summary', models.TextField(help_text='Enter summary to display on home page when featured')),
                ('display_image', models.ImageField(default=1, upload_to='images/')),
                ('image_alt', models.CharField(help_text='Enter alt text to display on mouse over of feature image', max_length=200)),
                ('button_variable', models.CharField(help_text='Enter variable to pass to map application which will enable the selected data type on the map', max_length=200)),
                ('button_text', models.CharField(help_text='Enter text of button to access data on map', max_length=200)),
                ('metadata_id', models.CharField(help_text='Enter metadata id from GeoNetwork', max_length=200)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(help_text='Type of dataset (currently Model or Observation)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title which will display in the layer list on the map application', max_length=200)),
                ('url', models.TextField(help_text='Enter url to the TDS WMS service')),
                ('attribution', models.TextField(help_text='Enter data attribution to display in map UI')),
                ('layers', models.CharField(help_text='Enter layer names from the WMS to display', max_length=200)),
                ('default_style', models.CharField(help_text='Enter default style to use for WMS to display', max_length=200)),
                ('default_color_range', models.CharField(help_text='Enter default color range to use for WMS to display', max_length=200)),
                ('ui_id', models.CharField(help_text='ID for the UI to use and access in javascript', max_length=200)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='frontend.dataset')),
                ('dataset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datatype', to='frontend.datasettype')),
            ],
        ),
    ]
