# Generated by Django 3.2.6 on 2021-09-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title which will display in the layer list on the map application', max_length=200)),
                ('url', models.TextField(help_text='Enter url to the TDS WMS service')),
                ('attribution', models.TextField(help_text='Enter data attribution to display in map UI')),
                ('layers', models.CharField(help_text='Enter layer names from the WMS to display', max_length=200)),
                ('units', models.CharField(default='Dimensionless', help_text='Enter units to display on chart', max_length=200)),
                ('default_style', models.CharField(help_text='Enter default style to use for WMS to display', max_length=200)),
                ('default_color_range', models.CharField(help_text='Enter default color range to use for WMS to display', max_length=200)),
                ('ui_id', models.CharField(help_text='ID for the UI to use and access in javascript', max_length=200)),
                ('api_id', models.CharField(default='', help_text='Enter API ID used to identify this data layer', max_length=200)),
                ('isMultiEnsemble', models.BooleanField(default=False, help_text='This is the main entry to the model ensembles')),
                ('hasVisualization', models.BooleanField(default=True, help_text='Indicates if the layer has wms capabilities.')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', help_text='Enter a short name to identify the dataset', max_length=200)),
                ('heading', models.CharField(help_text='Enter heading to display on home page when featured', max_length=200)),
                ('feature_subtext', models.TextField(default='', help_text='Enter subtext to display on home page when featured')),
                ('summary', models.TextField(default='', help_text='Enter summary to display in help center card')),
                ('display_image', models.ImageField(default='images/no_data_preview.png', upload_to='images/')),
                ('image_alt', models.CharField(help_text='Enter alt text to display on mouse over of feature image', max_length=200)),
                ('button_variable', models.CharField(help_text='Enter variable to pass to map application which will enable the selected data type on the map', max_length=200)),
                ('button_text', models.CharField(help_text='Enter text of button to access data on map', max_length=200)),
                ('metadata_id', models.CharField(help_text='Enter metadata id from GeoNetwork', max_length=200)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(help_text='Type of dataset (currently Model or Observation)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Enter a title which will display in the hero image.', max_length=200)),
                ('hero_subtitle', models.CharField(help_text='Enter a subtitle which will display in the hero image.', max_length=200)),
                ('hero_image', models.ImageField(default='images/no_data_preview.png', upload_to='images/')),
                ('intro_text_header', models.CharField(help_text='Header for intro section.', max_length=200)),
                ('intro_text', models.TextField(help_text='Paragraph for intro text')),
            ],
        ),
        migrations.CreateModel(
            name='WhatYouCanDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for the section.', max_length=200)),
                ('body', models.TextField(help_text='Enter the body.')),
                ('display_image', models.ImageField(default='images/no_data_preview.png', upload_to='images/')),
                ('HomePage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='frontend.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='EnsembleLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title which will display in the layer list on the map application', max_length=200)),
                ('url', models.TextField(help_text='Enter url to the TDS WMS service')),
                ('attribution', models.TextField(help_text='Enter data attribution to display in map UI')),
                ('layers', models.CharField(help_text='Enter layer names from the WMS to display', max_length=200)),
                ('units', models.CharField(default='Dimensionless', help_text='Enter units to display on chart', max_length=200)),
                ('default_style', models.CharField(help_text='Enter default style to use for WMS to display', max_length=200)),
                ('default_color_range', models.CharField(help_text='Enter default color range to use for WMS to display', max_length=200)),
                ('ui_id', models.CharField(help_text='Please use lowercase master title + ens + number. IE: nmmeens1', max_length=200)),
                ('api_id', models.CharField(default='', help_text='Enter API ID used to identify this data layer', max_length=200)),
                ('master_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalayer', to='frontend.datalayer')),
            ],
        ),
        migrations.AddField(
            model_name='datalayer',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='frontend.dataset'),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='dataset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datatype', to='frontend.datasettype'),
        ),
    ]
