# Generated by Django 3.2.4 on 2021-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='feature_subtext',
            field=models.TextField(default='', help_text='Enter subtext to display on home page when featured'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='summary',
            field=models.TextField(default='', help_text='Enter summary to display in help center card'),
        ),
    ]
