# Generated by Django 3.2.6 on 2021-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='yAxis_Special_Formatting',
            field=models.TextField(default="", help_text='Only include if your yAxis needs special formatting, this should be a json object with the key formatter: function () and the function should return the formatted value'),
        ),
    ]
