# Generated by Django 3.2.6 on 2021-09-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_datalayer_yaxis_special_formatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='graph_point_Special_Formatting',
            field=models.TextField(default='', help_text="Only include if your graph point needs special formatting, this should be a string describing the format like 'Value: {point.y:.2f} mm'"),
        ),
    ]
