# Generated by Django 3.2.6 on 2022-02-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_ensemblelayer_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensemblelayer',
            name='sample',
        ),
    ]
