# Generated by Django 3.2.4 on 2021-07-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210715_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='api_id',
            field=models.CharField(default='', help_text='Enter API ID used to identify this data layer', max_length=200),
        ),
    ]
