# Generated by Django 3.2.4 on 2021-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_datalayer_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='short_name',
            field=models.CharField(default='', help_text='Enter a short name to identify the dataset', max_length=200),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='heading',
            field=models.CharField(help_text='Enter heading to display on home page when featured', max_length=200),
        ),
    ]
