# Generated by Django 3.2.6 on 2021-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_datalayer_graph_point_special_formatting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='graph_point_Special_Formatting',
            field=models.TextField(blank=True, default='', help_text='Only include if your graph point needs special formatting, , this should be a json object with the key {pointFormatter: function() nd the function should return the formatted value'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='yAxis_Special_Formatting',
            field=models.TextField(blank=True, default='', help_text='Only include if your yAxis needs special formatting, this should be a json object with the key formatter: function () and the function should return the formatted value'),
        ),
    ]
