# Generated by Django 3.2.4 on 2021-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210705_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dataset_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='short_name',
            field=models.CharField(default='Unnamed', help_text='Enter a short name to identify the dataset', max_length=200),
        ),
    ]
