# Generated by Django 3.2.4 on 2021-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_dataset_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='units',
            field=models.CharField(default='Dimensionless', help_text='Enter units to display on chart', max_length=200),
        ),
    ]
