# Generated by Django 3.2.4 on 2021-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210708_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_image',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='image_src',
            field=models.CharField(default='', help_text='trying to remove this', max_length=200),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='short_name',
            field=models.CharField(default='Enter-Name', help_text='Enter a short name to identify the dataset', max_length=200),
        ),
    ]
