# Generated by Django 3.2.4 on 2021-07-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210708_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='image_src',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
