# Generated by Django 3.2.15 on 2022-10-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_ensemblelayer_etl_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemblelayer',
            name='dataset_name_format',
            field=models.CharField(blank=True, help_text='Dataset file name', max_length=255),
        ),
        migrations.AddField(
            model_name='ensemblelayer',
            name='ensemble_definition',
            field=models.JSONField(blank=True, default=dict, help_text='This json object must contain the key named data which must be \n    an array.  Inside the array there must be a list of json objects which contain api_id,and variable', verbose_name='Ensemble IDs and Variables'),
        ),
        migrations.AddField(
            model_name='ensemblelayer',
            name='fast_directory_path',
            field=models.TextField(default='/mnt/climateserv/process_tmp/fast_chirps/', verbose_name='Fast directory Path'),
        ),
        migrations.AlterField(
            model_name='ensemblelayer',
            name='api_id',
            field=models.CharField(default='', help_text='Enter lowest variable API ID from the above json object', max_length=200),
        ),
        migrations.AlterField(
            model_name='ensemblelayer',
            name='title',
            field=models.CharField(help_text='Enter a title which will display in the layer list on the map\n     application', max_length=200),
        ),
    ]
