# Generated by Django 3.2.4 on 2021-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_datalayer_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='isMultiEnsemble',
            field=models.BooleanField(default=False),
        ),
    ]
