# Generated by Django 3.2.4 on 2021-08-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_datalayer_ismultiensemble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='isMultiEnsemble',
            field=models.BooleanField(default=False, help_text='This is the main entry to the maodel ensembles'),
        ),
        migrations.CreateModel(
            name='EnsembleLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title which will display in the layer list on the map application', max_length=200)),
                ('url', models.TextField(help_text='Enter url to the TDS WMS service')),
                ('attribution', models.TextField(help_text='Enter data attribution to display in map UI')),
                ('layers', models.CharField(help_text='Enter layer names from the WMS to display', max_length=200)),
                ('units', models.CharField(default='Dimensionless', help_text='Enter units to display on chart', max_length=200)),
                ('default_style', models.CharField(help_text='Enter default style to use for WMS to display', max_length=200)),
                ('default_color_range', models.CharField(help_text='Enter default color range to use for WMS to display', max_length=200)),
                ('ui_id', models.CharField(help_text='ID for the UI to use and access in javascript', max_length=200)),
                ('api_id', models.CharField(default='', help_text='Enter API ID used to identify this data layer', max_length=200)),
                ('master_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalayer', to='frontend.datalayer')),
            ],
        ),
    ]
