# Generated by Django 3.2.4 on 2021-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210708_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='image_src',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_image',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
    ]
