# Generated by Django 3.2.15 on 2023-10-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_ensemblelayer_etl_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='availability',
            field=models.CharField(default='', help_text='String field Interval from X to Z', max_length=512),
        ),
    ]
