# Generated by Django 3.2.4 on 2021-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210811_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='short_name',
            field=models.CharField(default='', help_text='Enter a short name to identify the dataset', max_length=200),
        ),
        migrations.AlterField(
            model_name='ensemblelayer',
            name='ui_id',
            field=models.CharField(help_text='Please use lowercase master title + ens + number. IE: nmmeens1', max_length=200),
        ),
    ]
