# Generated by Django 3.2.20 on 2024-12-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_datalayer_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='isLegacyThredds',
            field=models.BooleanField(default=True, help_text='Indicates if the layer has legacy THREDDS WMS.'),
        ),
    ]
