# Generated by Django 3.2.4 on 2021-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210812_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='hasVisualization',
            field=models.BooleanField(default=True, help_text='Indicates if the layer has wms capabilities.'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='isMultiEnsemble',
            field=models.BooleanField(default=False, help_text='This is the main entry to the model ensembles'),
        ),
    ]
