# Generated by Django 3.2.6 on 2021-09-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210815_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Enter a title which will display in the hero image.', max_length=200)),
                ('hero_subtitle', models.CharField(help_text='Enter a subtitle which will display in the hero image.', max_length=200)),
                ('hero_image', models.ImageField(default='images/no_data_preview.png', upload_to='images/')),
                ('intro_text_header', models.CharField(help_text='Header for intro section.', max_length=200)),
                ('intro_text', models.TextField(help_text='Paragraph for intro text')),
            ],
        ),
        migrations.CreateModel(
            name='WhatYouCanDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for the section.', max_length=200)),
                ('body', models.TextField(help_text='Enter the body.', max_length=200)),
                ('display_image', models.ImageField(default='images/no_data_preview.png', upload_to='images/')),
                ('HomePage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='frontend.homepage')),
            ],
        ),
    ]
