# Generated by Django 3.2.6 on 2021-09-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_homepage_whatyoucando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoucando',
            name='body',
            field=models.TextField(help_text='Enter the body.'),
        ),
    ]
