# Generated by Django 3.2.4 on 2021-07-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_dataset_dataset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='image_src',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
